<a href="https://colab.research.google.com/github/AnnaBozhenko/ML_course/blob/master/00_pyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello, I'm excited to be honest.")

Hello, I'm excited to be honest.


In [ ]:
import torch
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

print(torch.__version__)

2.2.1+cu121


In [ ]:
scalar = torch.tensor(2)
print(scalar)
print(scalar.ndim)
print(scalar.shape)

tensor(2)
0
torch.Size([])


In [ ]:
vector = torch.tensor([1, 2, 3])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([1, 2, 3])
1
torch.Size([3])


In [ ]:
matrix = torch.tensor([ [
                          [1, 2, 3],
                          [4, 5, 6]
                        ],
                        [
                          [11, 32, 93],
                          [41, 54, 65]
                        ]
                      ])
matrix[1][0]

tensor([11, 32, 93])

In [ ]:
X = torch.rand(3, 4)

In [ ]:
X

tensor([[0.9277, 0.7898, 0.3674, 0.6521],
        [0.0816, 0.4435, 0.2635, 0.0642],
        [0.7028, 0.5264, 0.4412, 0.0638]])

In [ ]:
torch.rand(5, 2, 3, 3)

tensor([[[[0.1689, 0.3355, 0.4175],
          [0.1223, 0.2007, 0.8313],
          [0.7140, 0.8165, 0.4043]],

         [[0.9623, 0.4184, 0.7704],
          [0.3634, 0.0592, 0.7924],
          [0.8332, 0.5488, 0.6806]]],


        [[[0.4816, 0.1580, 0.4995],
          [0.4957, 0.9754, 0.5683],
          [0.7242, 0.5562, 0.3596]],

         [[0.6762, 0.1204, 0.7782],
          [0.3828, 0.4484, 0.1994],
          [0.7937, 0.1343, 0.8634]]],


        [[[0.8800, 0.9403, 0.0333],
          [0.0138, 0.6353, 0.3992],
          [0.1528, 0.1168, 0.8542]],

         [[0.2756, 0.4346, 0.3268],
          [0.0450, 0.1001, 0.2291],
          [0.6161, 0.0155, 0.9046]]],


        [[[0.7720, 0.4192, 0.6604],
          [0.0323, 0.6458, 0.0700],
          [0.9006, 0.8715, 0.4135]],

         [[0.5609, 0.9451, 0.2042],
          [0.7046, 0.4953, 0.9166],
          [0.1311, 0.5611, 0.6738]]],


        [[[0.2843, 0.4871, 0.9533],
          [0.0394, 0.8981, 0.2420],
          [0.5526, 0.6728, 0.9374]],

  

In [ ]:
zeros_t = torch.zeros(size=(2, 3, 1))
ones_t = torch.ones(size=(5, 2))

In [ ]:
zeros_t

tensor([[[0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.]]])

In [ ]:
ones_t

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [ ]:
tensor_32 = torch.tensor([1.34, 3.9, 23.9],
                         dtype=None,
                         device=None,
                         requires_grad=False)

In [ ]:
tensor_32.dtype

torch.float32

In [ ]:
tensor_16 = tensor_32.type(torch.float16)

In [ ]:
tensor_16

tensor([ 1.3398,  3.9004, 23.9062], dtype=torch.float16)

In [ ]:
tensor_32


tensor([ 1.3400,  3.9000, 23.9000])

In [ ]:
torch.multiply(tensor_32, tensor_16)

tensor([  1.7954,  15.2115, 571.3594])

In [ ]:
a = tensor_32 * tensor_16

In [ ]:
a.dtype

torch.float32

In [ ]:
int_tensor_32 = torch.tensor([1, 56, 7], dtype=torch.int32)

In [ ]:
b = tensor_32 * int_tensor_32

NameError: name 'tensor_32' is not defined

In [ ]:
b.dtype

torch.float32

In [ ]:
int_tensor_64 = int_tensor_32.type(torch.int64)

In [ ]:
c = int_tensor_32 * int_tensor_64

In [ ]:
int_tensor_16 = int_tensor_32.type(torch.int16)

In [ ]:
d = tensor_32 * int_tensor_16

In [ ]:
c.dtype

torch.int64

In [ ]:
d.dtype

torch.float32

In [ ]:
e = torch.tensor([23, 45.7, 4],
                 dtype=torch.float64,
                 device = "cuda")

In [ ]:
e

tensor([23.0000, 45.7000,  4.0000], device='cuda:0', dtype=torch.float64)

# tensor multiplication

In [ ]:
a = torch.tensor([[1, 2, 45.8],
                  [1, 2, 45.8],
                  [1, 2, 45.8]])

In [ ]:
b = torch.tensor([[1, 2, 3, 5],
                  [1, 2, 3, 5],
                  [1, 2, 3, 5]], dtype=torch.float32)

In [ ]:
%%time
torch.matmul(a, b)

CPU times: user 0 ns, sys: 1.67 ms, total: 1.67 ms
Wall time: 15.6 ms


tensor([[ 48.8000,  97.6000, 146.4000, 244.0000],
        [ 48.8000,  97.6000, 146.4000, 244.0000],
        [ 48.8000,  97.6000, 146.4000, 244.0000]])

In [ ]:
a @ b

tensor([[ 48.8000,  97.6000, 146.4000, 244.0000],
        [ 48.8000,  97.6000, 146.4000, 244.0000],
        [ 48.8000,  97.6000, 146.4000, 244.0000]])

tensors manipulation


In [ ]:
x = torch.arange(10)

In [ ]:
stacked = torch.stack([x, x, x], dim=0)
stacked = torch.stack([stacked, stacked], dim=1)

In [ ]:
stacked.shape

torch.Size([3, 2, 10])

In [ ]:
stacked

tensor([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
         [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]],

        [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
         [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]],

        [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
         [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]])

In [ ]:
torch.stack([stacked, stacked], dim=2)

tensor([[[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
          [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]],

         [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
          [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]],


        [[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
          [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]],

         [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
          [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]],


        [[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
          [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]],

         [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
          [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]]])

In [ ]:
stacked

tensor([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
         [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]],

        [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
         [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]],

        [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
         [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]])

In [ ]:
stacked.shape

torch.Size([3, 2, 10])

In [ ]:
stacked.squeeze()

tensor([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
         [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]],

        [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
         [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]],

        [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
         [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]])

In [ ]:
reshaped_stacked_0 = stacked.reshape([1, 60])

In [ ]:
reshaped_stacked_1 = stacked.reshape([1, 1, 60])

In [ ]:
reshaped_stacked_0

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3,
         4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7,
         8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
reshaped_stacked_1

tensor([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2,
          3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5,
          6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]])

In [ ]:
a = reshaped_stacked_0.squeeze()

In [ ]:
b = reshaped_stacked_1.squeeze()

In [ ]:
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3,
        4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7,
        8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3,
        4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7,
        8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
c = torch.rand([224, 224, 3])

In [ ]:
permuted_c = c.permute(dims=(2, 1, 0))

In [ ]:
c

tensor([[[0.3208, 0.8172, 0.5816],
         [0.8611, 0.9441, 0.5828],
         [0.0831, 0.9177, 0.3142],
         ...,
         [0.2695, 0.4458, 0.7589],
         [0.2948, 0.1285, 0.6703],
         [0.8244, 0.7419, 0.9949]],

        [[0.3398, 0.0393, 0.2774],
         [0.4315, 0.7911, 0.1398],
         [0.5137, 0.9309, 0.5728],
         ...,
         [0.6276, 0.3650, 0.5650],
         [0.8556, 0.5808, 0.0951],
         [0.3755, 0.4752, 0.5743]],

        [[0.8403, 0.3052, 0.4685],
         [0.4257, 0.0291, 0.9425],
         [0.1903, 0.5858, 0.5782],
         ...,
         [0.9473, 0.7272, 0.6107],
         [0.1290, 0.4622, 0.9888],
         [0.8124, 0.2735, 0.7570]],

        ...,

        [[0.0104, 0.9112, 0.3104],
         [0.2335, 0.5855, 0.6217],
         [0.9769, 0.7650, 0.5292],
         ...,
         [0.5694, 0.6438, 0.1783],
         [0.0192, 0.4749, 0.6678],
         [0.9778, 0.1438, 0.6129]],

        [[0.8698, 0.5342, 0.8176],
         [0.7761, 0.8613, 0.5434],
         [0.

In [ ]:
permuted_c

tensor([[[0.3208, 0.3398, 0.8403,  ..., 0.0104, 0.8698, 0.5329],
         [0.8611, 0.4315, 0.4257,  ..., 0.2335, 0.7761, 0.1960],
         [0.0831, 0.5137, 0.1903,  ..., 0.9769, 0.2527, 0.3255],
         ...,
         [0.2695, 0.6276, 0.9473,  ..., 0.5694, 0.6094, 0.9757],
         [0.2948, 0.8556, 0.1290,  ..., 0.0192, 0.3970, 0.6709],
         [0.8244, 0.3755, 0.8124,  ..., 0.9778, 0.4042, 0.3901]],

        [[0.8172, 0.0393, 0.3052,  ..., 0.9112, 0.5342, 0.0655],
         [0.9441, 0.7911, 0.0291,  ..., 0.5855, 0.8613, 0.9791],
         [0.9177, 0.9309, 0.5858,  ..., 0.7650, 0.4233, 0.5025],
         ...,
         [0.4458, 0.3650, 0.7272,  ..., 0.6438, 0.1610, 0.0971],
         [0.1285, 0.5808, 0.4622,  ..., 0.4749, 0.2143, 0.2748],
         [0.7419, 0.4752, 0.2735,  ..., 0.1438, 0.6648, 0.8302]],

        [[0.5816, 0.2774, 0.4685,  ..., 0.3104, 0.8176, 0.4305],
         [0.5828, 0.1398, 0.9425,  ..., 0.6217, 0.5434, 0.8837],
         [0.3142, 0.5728, 0.5782,  ..., 0.5292, 0.3769, 0.

device = "cuda" if torch.cuda.is_available() else "cpu"

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"

'cpu'

In [ ]:
t = torch.arange(4)

In [ ]:
t

tensor([0, 1, 2, 3])

In [ ]:
t.to(device)

tensor([0, 1, 2, 3])

In [ ]:
t.numpy()

array([0, 1, 2, 3])

Exercises


In [ ]:
random_t = torch.rand([7, 7])

In [ ]:
random_t

tensor([[0.3971, 0.0085, 0.6934, 0.6852, 0.7827, 0.9984, 0.8433],
        [0.6569, 0.6906, 0.0379, 0.0752, 0.2615, 0.6140, 0.9420],
        [0.7230, 0.3095, 0.6041, 0.7569, 0.7029, 0.7015, 0.9996],
        [0.7447, 0.2365, 0.8901, 0.2108, 0.1571, 0.5677, 0.3053],
        [0.1443, 0.6873, 0.7332, 0.6549, 0.3041, 0.8646, 0.8178],
        [0.8990, 0.7864, 0.1130, 0.3749, 0.8582, 0.0066, 0.6859],
        [0.1937, 0.7821, 0.8102, 0.3889, 0.4182, 0.1713, 0.3818]])

In [ ]:
t = random_t[0, :].reshape(7, 1)

In [ ]:
t

tensor([[0.3971],
        [0.0085],
        [0.6934],
        [0.6852],
        [0.7827],
        [0.9984],
        [0.8433]])

In [ ]:
multiplied_tensors = torch.matmul(random_t, t)

In [ ]:
SEED = 23



In [ ]:
def routine_3():
  torch.manual_seed(SEED)
  rand_t = torch.rand([7, 7])
  t = rand_t[0, :].reshape([7, 1])
  print(f"rand_t:\n {rand_t}")
  print(f"t:\n {t}")
  maltiplied_tensors = torch.matmul(rand_t, t)
  print(f"rand_t @ t:\n {maltiplied_tensors}")


In [ ]:
routine_3()

rand_t:
 tensor([[0.4283, 0.2889, 0.4224, 0.3571, 0.9577, 0.1100, 0.2933],
        [0.9205, 0.5876, 0.1299, 0.6729, 0.1028, 0.7876, 0.5540],
        [0.4653, 0.2311, 0.2214, 0.3348, 0.4541, 0.2519, 0.6310],
        [0.1707, 0.3122, 0.1976, 0.5466, 0.0213, 0.9049, 0.8444],
        [0.9330, 0.2950, 0.4773, 0.4787, 0.3440, 0.6732, 0.6593],
        [0.1879, 0.4546, 0.1049, 0.7112, 0.7709, 0.5514, 0.0807],
        [0.3029, 0.7935, 0.2823, 0.5686, 0.1354, 0.4224, 0.1946]])
t:
 tensor([[0.4283],
        [0.2889],
        [0.4224],
        [0.3571],
        [0.9577],
        [0.1100],
        [0.2933]])
rand_t @ t:
 tensor([[1.5881],
        [1.2066],
        [1.1268],
        [0.8095],
        [1.4542],
        [1.3327],
        [0.9143]])


In [ ]:
routine_3()

rand_t:
 tensor([[0.4283, 0.2889, 0.4224, 0.3571, 0.9577, 0.1100, 0.2933],
        [0.9205, 0.5876, 0.1299, 0.6729, 0.1028, 0.7876, 0.5540],
        [0.4653, 0.2311, 0.2214, 0.3348, 0.4541, 0.2519, 0.6310],
        [0.1707, 0.3122, 0.1976, 0.5466, 0.0213, 0.9049, 0.8444],
        [0.9330, 0.2950, 0.4773, 0.4787, 0.3440, 0.6732, 0.6593],
        [0.1879, 0.4546, 0.1049, 0.7112, 0.7709, 0.5514, 0.0807],
        [0.3029, 0.7935, 0.2823, 0.5686, 0.1354, 0.4224, 0.1946]])
t:
 tensor([[0.4283],
        [0.2889],
        [0.4224],
        [0.3571],
        [0.9577],
        [0.1100],
        [0.2933]])
rand_t @ t:
 tensor([[1.5881],
        [1.2066],
        [1.1268],
        [0.8095],
        [1.4542],
        [1.3327],
        [0.9143]])


In [ ]:
!nvidia-smi

Wed May 15 10:44:36 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   63C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
rand_gpu_t = torch.rand([7,7])

In [ ]:
import torch

In [ ]:
SEED = 1234

In [ ]:
torch.cuda.manual_seed(SEED)

In [ ]:
torch.manual_seed(SEED)
gpu_powered_tensor_1 = torch.rand([2, 3], device="cuda")

In [ ]:
gpu_powered_tensor_2 = torch.rand([2, 3], device="cuda")

In [ ]:
multiplied_gpu_powered_tensors = gpu_powered_tensor_1 @ torch.transpose(gpu_powered_tensor_2, 0, 1)

In [ ]:
multiplied_gpu_powered_tensors

tensor([[0.2786, 0.7668],
        [0.7343, 0.6102]], device='cuda:0')

In [ ]:
max_value = multiplied_gpu_powered_tensors.max()
max_value

tensor(0.7668, device='cuda:0')

In [ ]:
min_value = multiplied_gpu_powered_tensors.min()
min_value

tensor(-1., device='cuda:0')

In [ ]:
argmax_value = multiplied_gpu_powered_tensors.argmax()
argmax_value

tensor(1, device='cuda:0')

In [ ]:
argmin_value = multiplied_gpu_powered_tensors.argmin()
argmin_value

tensor(2, device='cuda:0')

In [ ]:
multiplied_gpu_powered_tensors[1, 0] = -1

In [ ]:
multiplied_gpu_powered_tensors

tensor([[ 0.2786,  0.7668],
        [-1.0000,  0.6102]], device='cuda:0')

In [ ]:
torch.manual_seed(7)
t1 = torch.rand([1, 1, 1, 10])
print(f"shape before squeezing:\n {t1.shape}")
t1 = t1.squeeze()
print(f"shape after squezzing:\n {t1.shape}")

shape before squeezing:
 torch.Size([1, 1, 1, 10])
shape after squezzing:
 torch.Size([10])
